theme: jekyll-theme-slate
title: [Olha Kaminska homepage](https://olha-kaminska.github.io/)
description: The personal blog about PhD experience in Natural Language Processing
email: Olha.Kaminska@uGent.be
url: http://olha-kaminska.github.io
github_username: olha-kaminska
