theme: jekyll-theme-slate
title: Welcome to Olha Kaminska homepage!
description: My personal blog about my experience during a PhD study in areas of Machine Learning and Natural Language Processing
email: Olha.Kaminska@uGent.be
url: "http://olha-kaminska.github.io"
github_username:  olha-kaminska
